import { Hono } from 'hono'
import { appendFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { getGroqClient } from '../lib/groq.js'

export const debugRouter = new Hono()

const LOG_PATH = join(process.cwd(), '..', 'renderer-debug.log')
try { writeFileSync(LOG_PATH, `=== Renderer Debug Log — ${new Date().toISOString()} ===\n`) } catch {}

debugRouter.post('/log', async (c) => {
  try {
    const { level, msg, src, line } = await c.req.json()
    const entry = `[${new Date().toISOString().slice(11, 23)}] [${(level ?? 'INFO').toUpperCase()}] ${msg}  (${src ?? ''}:${line ?? 0})\n`
    appendFileSync(LOG_PATH, entry)
  } catch {}
  return c.json({ ok: true })
})

// ─── Free models list ────────────────────────────────────────────────────────
const FREE_MODELS = [
  'llama-3.3-70b-versatile',
  'llama-3.1-8b-instant',
  'openai/gpt-oss-20b',
  'openai/gpt-oss-120b',
  'allam-2-7b',
]

debugRouter.get('/models', (c) => {
  return c.json({ models: FREE_MODELS.map(id => ({ id })) })
})

// ─── Test a single model ────────────────────────────────────────────────────
const TEST_PROMPTS: Record<string, string> = {
  question: `You are a senior interviewer. Based on this CV:
'Data engineer 5 years. Spark, Airflow, AWS, Databricks, Lakehouse, CDP.'
Ask ONE specific technical question about their real experience. No explanations, just the question.`,

  translate: `Translate to conversational Vietnamese (ONLY the translation, no explanations):
'Explain your approach to designing a scalable data pipeline that handles both real-time streaming and batch processing, ensuring data quality across multiple sources.'`,

  summary: `Summarize this conversation concisely (only the summary):
Q: Tell me about your background.
A: Data engineer 5 years at CDP. Built Lakehouse with Spark, Airflow, Databricks.
Q: What was your biggest challenge?
A: Optimizing Spark jobs for 10TB daily data, reduced runtime 40%.
Q: How did you handle data quality?
A: Implemented Great Expectations with Airflow DAGs for automated validation.`,
}

function hasReasoningTags(content: string): string[] {
  const tags: string[] = []
  if (/<think>[\s\S]*?<\/think>/i.test(content)) tags.push('<think>')
  if (/\|im_start\|>/i.test(content)) tags.push('im_start')
  if (/```reasoning/i.test(content)) tags.push('code-fence')
  if (/^Reasoning:/im.test(content)) tags.push('Reasoning:')
  return tags
}

function isVietnamese(text: string): boolean {
  return /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i.test(text)
}

debugRouter.post('/test-model', async (c) => {
  const { model, type = 'question' } = await c.req.json() as { model: string; type: string }
  if (!model) return c.json({ error: 'model is required' }, 400)
  const prompt = TEST_PROMPTS[type] || TEST_PROMPTS.question

  try {
    const start = Date.now()
    const isQwen = model.toLowerCase().includes('qwen')
    const r = await getGroqClient().chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model, max_tokens: 300, temperature: 0.3,
      ...(isQwen ? { reasoning_format: 'hidden' as any } : {}),
    } as any)
    const ms = Date.now() - start
    const rawContent = r.choices[0]?.message?.content?.trim() || ''
    if (!rawContent) {
      return c.json({ model, type, ms, content: '(empty response)', reasoning: null, vietnamese: null, chars: 0 })
    }
    const tags = hasReasoningTags(rawContent)
    const cleaned = rawContent
      .replace(/<think>[\s\S]*?<\/think>/g, '')
      .replace(/<\|im_start\|>thought[\s\S]*?<\|im_end\|>/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim()
    const content = cleaned || rawContent  // fallback to raw if stripping removed everything
    const vn = type === 'translate' ? isVietnamese(content) : null

    return c.json({
      model, type, ms, content,
      reasoning: tags.length > 0 ? tags : null,
      vietnamese: vn,
      chars: content.length,
    })
  } catch (err: any) {
    return c.json({
      model, type,
      error: err?.message || 'Request failed',
      status: err?.status || 0,
    }, 500)
  }
})

// ─── AI Ranking ────────────────────────────────────────────────────────────────
const RANK_PROMPTS: Record<string, string> = {
  question: `You are evaluating interview questions generated by different AI models.
Rank these questions from best to worst based on: technical depth, specificity to data engineering, how well they probe real experience, and whether they avoid generic/general questions.
Output format: one line per model. Each line: MODEL_NAME | SCORE (1-10) | BRIEF_REASON`,

  translate: `You are evaluating Vietnamese translations from different AI models.
Rank these translations from best to worst based on: natural Vietnamese fluency, accuracy of technical terms, conversational tone, and completeness.
Output format: one line per model. Each line: MODEL_NAME | SCORE (1-10) | BRIEF_REASON`,

  summary: `You are evaluating conversation summaries from different AI models.
Rank these summaries from best to worst based on: completeness (all key points retained), conciseness, clarity, and accuracy of technical details.
Output format: one line per model. Each line: MODEL_NAME | SCORE (1-10) | BRIEF_REASON`,
}

interface RankItem { model: string; content: string; ms: number; reasoning?: string[] | null; vietnamese?: boolean | null }

debugRouter.post('/rank-models', async (c) => {
  const { type = 'question', results } = await c.req.json() as { type: string; results: RankItem[] }
  if (!results?.length) return c.json({ error: 'results required' }, 400)
  if (!RANK_PROMPTS[type]) return c.json({ error: 'Invalid type' }, 400)

  const items = results.map(r =>
    `--- ${r.model} ---\n${r.content}\n(Speed: ${r.ms}ms${r.reasoning?.length ? `, Tags: ${r.reasoning.join(',')}` : ''}${r.vietnamese === true ? ', Vietnamese: yes' : ''})`
  ).join('\n\n')

  const prompt = `${RANK_PROMPTS[type]}\n\nModels to rank:\n\n${items}`

  try {
    const r = await getGroqClient().chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.3,
      max_tokens: 1000,
    })
    const output = r.choices[0]?.message?.content?.trim() || ''
    // Try parsing with | delimiter first, fallback to numbered list
    let rankings = output.split('\n')
      .filter(l => l.includes('|'))
      .map(l => {
        const [model, score, ...reason] = l.split('|').map(s => s.trim())
        return { model, score: parseFloat(score) || 0, reason: reason.join('|').trim() }
      })
      .filter(r => r.model && r.score)

    if (rankings.length === 0) {
      // Fallback: numbered list like "1. model_name - reason"
      rankings = output.split('\n')
        .map(l => l.replace(/^\d+[\.\)]\s*/, '').trim())
        .filter(l => l && !l.startsWith('#'))
        .map((l, i) => {
          const score = Math.max(1, 10 - i)
          return { model: l.split(/[-–—]/)[0]?.trim() || l, score, reason: l.split(/[-–—]/).slice(1).join('-').trim() }
        })
        .filter(r => r.model)
    }

    return c.json({ rankings, raw: output })
  } catch (err: any) {
    return c.json({ error: err?.message || 'Ranking failed' }, 500)
  }
})
